# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Aubin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthewaubin.com" # the base hostname & protocol for your site
timezone: America/New_York

# Collections
collections:
  performance:
    output: true
  video:
    output: true

defaults:
  - scope:
      path: ""
      type: performance
    values:
      performance_date: ""
      group: ""
      group_link: "#" # the hash here is used as sentinel value, a link is NOT rendered if it's present
  - scope:
      path: ""
      type: video
    values:
      video_title: ""
      video_link: ""
      weight: 0

# Build settings
markdown: kramdown
